name: "airqo_device_monitoring"
version: "1.0.0"
config-version: 2

profile: "airqo"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  airqo_device_monitoring:
    +materialized: view
    staging:
      +materialized: view
      +schema: staging
