version: '3.8'

# Production configuration with additional security and optimization settings
services:
  data-ingestion:
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1'
          memory: 1G

  data-processing:
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '2'
          memory: 4G


